/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev Login
         * @description Development-only sign-in. Disabled unless ARDENTUM_AUTH_MODE=dev (never in production).
         */
        post: operations["dev_login_api_v1_auth_dev_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_v1_datasets_get"];
        put?: never;
        /** Upload Dataset */
        post: operations["upload_dataset_api_v1_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_api_v1_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        /** Delete Dataset */
        delete: operations["delete_dataset_api_v1_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analytics
         * @description Per-asset historical statistics, correlation and covariance.
         */
        post: operations["analytics_api_v1_analytics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimise
         * @description Constrained mean-variance optimisation with explanation.
         */
        post: operations["optimise_api_v1_optimise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/frontier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Frontier
         * @description Constrained efficient frontier (optionally against the unconstrained frontier).
         */
        post: operations["frontier_api_v1_frontier_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/esg/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Esg Impact
         * @description Effect of ESG constraints on return, risk, Sharpe ratio and composition.
         */
        post: operations["esg_impact_api_v1_esg_impact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/montecarlo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Montecarlo
         * @description Seeded Monte Carlo simulation of portfolio wealth.
         */
        post: operations["montecarlo_api_v1_montecarlo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backtest
         * @description Walk-forward backtest with attribution.
         */
        post: operations["backtest_api_v1_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare
         * @description Side-by-side comparison of fixed-weight portfolios.
         */
        post: operations["compare_api_v1_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Portfolios */
        get: operations["list_portfolios_api_v1_portfolios_get"];
        put?: never;
        /** Create Portfolio */
        post: operations["create_portfolio_api_v1_portfolios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio */
        get: operations["get_portfolio_api_v1_portfolios__portfolio_id__get"];
        /** Update Portfolio */
        put: operations["update_portfolio_api_v1_portfolios__portfolio_id__put"];
        post?: never;
        /** Delete Portfolio */
        delete: operations["delete_portfolio_api_v1_portfolios__portfolio_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Portfolio */
        get: operations["export_portfolio_api_v1_portfolios__portfolio_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsRequest */
        AnalyticsRequest: {
            universe: components["schemas"]["UniverseSelection"];
            estimation?: components["schemas"]["EstimationSettings"];
            /** Benchmark */
            benchmark?: string | null;
        };
        /** AnalyticsResponse */
        AnalyticsResponse: {
            data: components["schemas"]["DataWindowOut"];
            estimation: components["schemas"]["EstimationOut"];
            /** Benchmark */
            benchmark: string | null;
            /** Assets */
            assets: components["schemas"]["AssetStatsOut"][];
            /** Tickers */
            tickers: string[];
            /** Correlation */
            correlation: number[][];
            /** Covariance */
            covariance: number[][];
            /** Price Dates */
            price_dates: string[];
            /** Normalised Prices */
            normalised_prices: {
                [key: string]: number[];
            };
        };
        /** AssetOut */
        AssetOut: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Asset Class */
            asset_class: string;
            /** Sector */
            sector: string | null;
            /** Currency */
            currency: string;
            /** Esg Score */
            esg_score: number | null;
            /** Esg Source */
            esg_source: string | null;
            /** Esg As Of */
            esg_as_of: string | null;
            /** Esg Is Synthetic */
            esg_is_synthetic: boolean;
            /** Is Benchmark */
            is_benchmark: boolean;
        };
        /** AssetStatsOut */
        AssetStatsOut: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string | null;
            /** Esg Score */
            esg_score: number | null;
            /** Expected Return */
            expected_return: number;
            performance: components["schemas"]["PerformanceOut"];
        };
        /** BacktestRequest */
        BacktestRequest: {
            universe: components["schemas"]["UniverseSelection"];
            estimation?: components["schemas"]["EstimationSettings"];
            /** Strategy */
            strategy: components["schemas"]["OptimisedStrategyIn"] | components["schemas"]["FixedStrategyIn"] | components["schemas"]["EqualWeightStrategyIn"];
            /**
             * Lookback Years
             * @default 3
             */
            lookback_years: number;
            /** @default monthly */
            rebalance: components["schemas"]["RebalanceFrequency"];
            /**
             * Transaction Cost Bps
             * @default 10
             */
            transaction_cost_bps: number;
            benchmark?: components["schemas"]["BenchmarkIn"] | null;
        };
        /** BacktestResponse */
        BacktestResponse: {
            /** Strategy */
            strategy: string;
            /** Dates */
            dates: string[];
            /** Wealth Dates */
            wealth_dates: string[];
            portfolio: components["schemas"]["SeriesOut"];
            benchmark: components["schemas"]["SeriesOut"] | null;
            performance: components["schemas"]["PerformanceOut"];
            benchmark_performance: components["schemas"]["PerformanceOut"] | null;
            /**
             * Estimation Start
             * Format: date
             */
            estimation_start: string;
            /**
             * Evaluation Start
             * Format: date
             */
            evaluation_start: string;
            /**
             * Evaluation End
             * Format: date
             */
            evaluation_end: string;
            /** Lookback Periods */
            lookback_periods: number;
            /** Rebalance */
            rebalance: string;
            /** Transaction Cost Bps */
            transaction_cost_bps: number;
            /** Total Cost */
            total_cost: number;
            /** Annualised Turnover */
            annualised_turnover: number;
            /** Events */
            events: components["schemas"]["RebalanceEventOut"][];
            /** Asset Contributions */
            asset_contributions: components["schemas"]["ContributionOut"][];
            /** Sector Contributions */
            sector_contributions: components["schemas"]["ContributionOut"][];
            /** Brinson */
            brinson: components["schemas"]["BrinsonOut"][] | null;
            /** Assumptions */
            assumptions: string[];
            data: components["schemas"]["DataWindowOut"];
        };
        /** BenchmarkIn */
        BenchmarkIn: {
            /**
             * Type
             * @default equal_weight
             * @enum {string}
             */
            type: "equal_weight" | "asset";
            /** Ticker */
            ticker?: string | null;
        };
        /** Body_upload_dataset_api_v1_datasets_post */
        Body_upload_dataset_api_v1_datasets_post: {
            /** Name */
            name: string;
            /**
             * Prices
             * @description CSV of adjusted close prices
             */
            prices: string;
            /** Description */
            description?: string | null;
            /**
             * Metadata
             * @description Optional asset metadata CSV
             */
            metadata?: string | null;
        };
        /** BrinsonOut */
        BrinsonOut: {
            /** Sector */
            sector: string;
            /** Allocation */
            allocation: number;
            /** Selection */
            selection: number;
            /** Interaction */
            interaction: number;
            /** Total */
            total: number;
            /** Portfolio Weight */
            portfolio_weight: number;
            /** Benchmark Weight */
            benchmark_weight: number;
        };
        /** CompareRequest */
        CompareRequest: {
            universe: components["schemas"]["UniverseSelection"];
            estimation?: components["schemas"]["EstimationSettings"];
            /** Portfolios */
            portfolios: components["schemas"]["PortfolioSpecIn"][];
            /** @default monthly */
            rebalance: components["schemas"]["RebalanceFrequency"];
            /**
             * Transaction Cost Bps
             * @default 0
             */
            transaction_cost_bps: number;
        };
        /** CompareResponse */
        CompareResponse: {
            /** Portfolios */
            portfolios: components["schemas"]["ComparedPortfolioOut"][];
            /** Dates */
            dates: string[];
            /** Wealth Dates */
            wealth_dates: string[];
            /** Return Correlation */
            return_correlation: number[][];
            /** In Sample Warning */
            in_sample_warning: string;
            estimation: components["schemas"]["EstimationOut"];
            data: components["schemas"]["DataWindowOut"];
        };
        /** ComparedPortfolioOut */
        ComparedPortfolioOut: {
            /** Name */
            name: string;
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** Expected Return */
            expected_return: number;
            /** Volatility */
            volatility: number;
            /** Sharpe Ratio */
            sharpe_ratio: number | null;
            /** Esg Score */
            esg_score: number | null;
            /** Effective Number Of Assets */
            effective_number_of_assets: number;
            /** Top Risk Contributors */
            top_risk_contributors: components["schemas"]["ContributionOut"][];
            historical: components["schemas"]["PerformanceOut"];
            /** Wealth */
            wealth: number[];
            /** Drawdown */
            drawdown: number[];
        };
        /** ConstraintDiagnosticOut */
        ConstraintDiagnosticOut: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Value */
            value: number;
            /** Bound */
            bound: number;
            /** Binding */
            binding: boolean;
            /** Assets */
            assets: string[];
            /** Shadow Price */
            shadow_price: number | null;
            /** Shadow Price Unit */
            shadow_price_unit: string | null;
        };
        /** ConstraintsIn */
        ConstraintsIn: {
            /**
             * Min Weight
             * @default 0
             */
            min_weight: number;
            /**
             * Max Weight
             * @default 1
             */
            max_weight: number;
            /** Asset Bounds */
            asset_bounds?: {
                [key: string]: [
                    number,
                    number
                ];
            };
            /** Sector Limits */
            sector_limits?: components["schemas"]["SectorLimitIn"][];
            /** Excluded Assets */
            excluded_assets?: string[];
            /** Excluded Sectors */
            excluded_sectors?: string[];
            /** Min Esg Score */
            min_esg_score?: number | null;
            /**
             * Esg Tilt
             * @description Annual return per 1 SD of ESG score.
             * @default 0
             */
            esg_tilt: number;
            /**
             * Exclude Unscored Assets
             * @default false
             */
            exclude_unscored_assets: boolean;
            /** Max Gross Exposure */
            max_gross_exposure?: number | null;
            tracking_error?: components["schemas"]["TrackingErrorIn"] | null;
        };
        /** ContributionOut */
        ContributionOut: {
            /** Name */
            name: string;
            /** Contribution */
            contribution: number;
        };
        /**
         * CovarianceEstimator
         * @enum {string}
         */
        CovarianceEstimator: "sample" | "ledoit_wolf" | "ledoit_wolf_constant_correlation";
        /** DataWindowOut */
        DataWindowOut: {
            /** Dataset Id */
            dataset_id: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Observations */
            observations: number;
            /** Frequency */
            frequency: string;
            /** Periods Per Year */
            periods_per_year: number;
            provenance: components["schemas"]["ProvenanceOut"];
            /** Quality Notes */
            quality_notes: string[];
            /** Quality Warnings */
            quality_warnings: string[];
        };
        /** DatasetOut */
        DatasetOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Description */
            description: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            provenance: components["schemas"]["ProvenanceOut"];
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Assets */
            assets: components["schemas"]["AssetOut"][];
            /** Sectors */
            sectors: string[];
            /**
             * Owned
             * @default false
             */
            owned: boolean;
        };
        /** DatasetSummaryOut */
        DatasetSummaryOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Description */
            description: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /** N Assets */
            n_assets: number;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /**
             * Owned
             * @default false
             */
            owned: boolean;
        };
        /** DevLoginRequest */
        DevLoginRequest: {
            /** Email */
            email: string;
        };
        /** EqualWeightStrategyIn */
        EqualWeightStrategyIn: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "equal_weight";
        };
        /** EsgFrontierPointOut */
        EsgFrontierPointOut: {
            /** Min Esg Score */
            min_esg_score: number;
            /** Feasible */
            feasible: boolean;
            /** Esg Score */
            esg_score: number | null;
            /** Expected Return */
            expected_return: number | null;
            /** Volatility */
            volatility: number | null;
            /** Sharpe Ratio */
            sharpe_ratio: number | null;
            /** Reason */
            reason: string | null;
        };
        /** EsgImpactRequest */
        EsgImpactRequest: {
            universe: components["schemas"]["UniverseSelection"];
            estimation?: components["schemas"]["EstimationSettings"];
            objective?: components["schemas"]["ObjectiveIn"];
            constraints: components["schemas"]["ConstraintsIn"];
            /** Esg Levels */
            esg_levels?: number[] | null;
        };
        /** EsgImpactResponse */
        EsgImpactResponse: {
            baseline: components["schemas"]["PortfolioResultOut"];
            esg: components["schemas"]["PortfolioResultOut"];
            /** Delta Expected Return */
            delta_expected_return: number;
            /** Delta Volatility */
            delta_volatility: number;
            /** Delta Sharpe Ratio */
            delta_sharpe_ratio: number | null;
            /** Delta Esg Score */
            delta_esg_score: number | null;
            /** Ex Ante Tracking Error */
            ex_ante_tracking_error: number;
            /** Ex Post Tracking Error */
            ex_post_tracking_error: number;
            /** Ex Post Tracking Error Note */
            ex_post_tracking_error_note: string;
            /** Weight Changes */
            weight_changes: components["schemas"]["WeightChangeOut"][];
            /** Sector Changes */
            sector_changes: {
                [key: string]: number | string;
            }[];
            /** Esg Frontier */
            esg_frontier: components["schemas"]["EsgFrontierPointOut"][];
            /** Esg Data Notes */
            esg_data_notes: string[];
            estimation: components["schemas"]["EstimationOut"];
            data: components["schemas"]["DataWindowOut"];
            /** Excluded Unscored */
            excluded_unscored: string[];
        };
        /** EstimationOut */
        EstimationOut: {
            /** Mean Estimator */
            mean_estimator: string;
            /** Covariance Estimator */
            covariance_estimator: string;
            /** Mean Shrinkage */
            mean_shrinkage: number | null;
            /** Covariance Shrinkage */
            covariance_shrinkage: number | null;
            /** Observations */
            observations: number;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
        };
        /** EstimationSettings */
        EstimationSettings: {
            /** @default historical */
            mean_estimator: components["schemas"]["MeanEstimator"];
            /** @default ledoit_wolf */
            covariance_estimator: components["schemas"]["CovarianceEstimator"];
            /**
             * Risk Free Rate
             * @description Effective annual rate.
             * @default 0
             */
            risk_free_rate: number;
        };
        /** ExplanationOut */
        ExplanationOut: {
            /** Objective Summary */
            objective_summary: string;
            /** Headline */
            headline: string;
            /** Statements */
            statements: string[];
            /** Warnings */
            warnings: string[];
            /** Assumptions */
            assumptions: string[];
        };
        /** FixedStrategyIn */
        FixedStrategyIn: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "fixed";
            /** Weights */
            weights: {
                [key: string]: number;
            };
        };
        /** FrontierAssetOut */
        FrontierAssetOut: {
            /** Ticker */
            ticker: string;
            /** Expected Return */
            expected_return: number;
            /** Volatility */
            volatility: number;
            /** Esg Score */
            esg_score: number | null;
            /** Sector */
            sector: string | null;
        };
        /** FrontierPointOut */
        FrontierPointOut: {
            /** Expected Return */
            expected_return: number;
            /** Volatility */
            volatility: number;
            /** Sharpe Ratio */
            sharpe_ratio: number | null;
            /** Esg Score */
            esg_score: number | null;
            /** Weights */
            weights: {
                [key: string]: number;
            };
        };
        /** FrontierRequest */
        FrontierRequest: {
            universe: components["schemas"]["UniverseSelection"];
            estimation?: components["schemas"]["EstimationSettings"];
            constraints?: components["schemas"]["ConstraintsIn"];
            /**
             * N Points
             * @default 30
             */
            n_points: number;
            /**
             * Compare Unconstrained
             * @default true
             */
            compare_unconstrained: boolean;
        };
        /** FrontierResponse */
        FrontierResponse: {
            /** Points */
            points: components["schemas"]["FrontierPointOut"][];
            min_volatility: components["schemas"]["FrontierPointOut"];
            max_sharpe: components["schemas"]["FrontierPointOut"] | null;
            /** Max Sharpe Unavailable Reason */
            max_sharpe_unavailable_reason: string | null;
            /** Unconstrained Points */
            unconstrained_points: components["schemas"]["FrontierPointOut"][] | null;
            /** Assets */
            assets: components["schemas"]["FrontierAssetOut"][];
            /** Risk Free Rate */
            risk_free_rate: number;
            /** Risk Free Rate Arithmetic */
            risk_free_rate_arithmetic: number;
            /** Warnings */
            warnings: string[];
            estimation: components["schemas"]["EstimationOut"];
            data: components["schemas"]["DataWindowOut"];
            /** Excluded Unscored */
            excluded_unscored: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistogramOut */
        HistogramOut: {
            /** Edges */
            edges: number[];
            /** Counts */
            counts: number[];
        };
        /** HoldingOut */
        HoldingOut: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string | null;
            /** Weight */
            weight: number;
            /** Expected Return */
            expected_return: number;
            /** Volatility */
            volatility: number;
            /** Esg Score */
            esg_score: number | null;
            /** Risk Contribution */
            risk_contribution: number;
            /** Risk Contribution Pct */
            risk_contribution_pct: number;
            /** Marginal Contribution */
            marginal_contribution: number;
            /** Beta To Portfolio */
            beta_to_portfolio: number;
            /** Required Return */
            required_return: number | null;
            /** Status */
            status: string;
            /** Reason */
            reason: string;
        };
        /** MeOut */
        MeOut: {
            /** User Id */
            user_id: string;
            /** Email */
            email: string | null;
        };
        /**
         * MeanEstimator
         * @enum {string}
         */
        MeanEstimator: "historical" | "bayes_stein";
        /** MetaOut */
        MetaOut: {
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /** Auth Mode */
            auth_mode: string;
            /** Supabase Url */
            supabase_url: string | null;
            /** Live Data Available */
            live_data_available: boolean;
            /** Methodology Version */
            methodology_version: string;
        };
        /** MetricOut */
        MetricOut: {
            /** Value */
            value: number | null;
            /** Reason */
            reason: string | null;
        };
        /** MonteCarloRequest */
        MonteCarloRequest: {
            universe: components["schemas"]["UniverseSelection"];
            estimation?: components["schemas"]["EstimationSettings"];
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** @default parametric */
            method: components["schemas"]["SimulationMethod"];
            /**
             * N Paths
             * @default 5000
             */
            n_paths: number;
            /**
             * Horizon Years
             * @default 10
             */
            horizon_years: number;
            /**
             * Initial Value
             * @default 10000
             */
            initial_value: number;
            /** Target Value */
            target_value?: number | null;
            /**
             * Mean Block Length
             * @default 21
             */
            mean_block_length: number;
            /** Seed */
            seed?: number | null;
        };
        /** MonteCarloResponse */
        MonteCarloResponse: {
            /** Method */
            method: string;
            /** Seed */
            seed: number;
            /** N Paths */
            n_paths: number;
            /** Horizon Years */
            horizon_years: number;
            /** Initial Value */
            initial_value: number;
            /** Times Years */
            times_years: number[];
            /** Percentiles */
            percentiles: {
                [key: string]: number[];
            };
            /** Mean Path */
            mean_path: number[];
            /** Sample Paths */
            sample_paths: number[][];
            terminal_histogram: components["schemas"]["HistogramOut"];
            /** Terminal Percentiles */
            terminal_percentiles: {
                [key: string]: number;
            };
            /** Probability Of Loss */
            probability_of_loss: number;
            /** Probability Of Target */
            probability_of_target: number | null;
            /** Target Value */
            target_value: number | null;
            /** Terminal Return Var 95 */
            terminal_return_var_95: number;
            /** Terminal Return Cvar 95 */
            terminal_return_cvar_95: number;
            /** Cagr Percentiles */
            cagr_percentiles: {
                [key: string]: number;
            };
            /** Max Drawdown Percentiles */
            max_drawdown_percentiles: {
                [key: string]: number;
            };
            /** Portfolio Expected Return */
            portfolio_expected_return: number;
            /** Portfolio Volatility */
            portfolio_volatility: number;
            /** Assumptions */
            assumptions: string[];
            data: components["schemas"]["DataWindowOut"];
        };
        /**
         * Objective
         * @enum {string}
         */
        Objective: "min_volatility" | "max_sharpe" | "target_return" | "target_volatility" | "max_utility";
        /** ObjectiveIn */
        ObjectiveIn: {
            /** @default max_sharpe */
            objective: components["schemas"]["Objective"];
            /** Target Return */
            target_return?: number | null;
            /** Target Volatility */
            target_volatility?: number | null;
            /** Risk Aversion */
            risk_aversion?: number | null;
        };
        /** OptimiseRequest */
        OptimiseRequest: {
            universe: components["schemas"]["UniverseSelection"];
            estimation?: components["schemas"]["EstimationSettings"];
            objective?: components["schemas"]["ObjectiveIn"];
            constraints?: components["schemas"]["ConstraintsIn"];
            /**
             * Stability Resamples
             * @default 0
             */
            stability_resamples: number;
            /** Seed */
            seed?: number | null;
        };
        /** OptimiseResponse */
        OptimiseResponse: {
            result: components["schemas"]["PortfolioResultOut"];
            explanation: components["schemas"]["ExplanationOut"];
            estimation: components["schemas"]["EstimationOut"];
            data: components["schemas"]["DataWindowOut"];
            /** Excluded Unscored */
            excluded_unscored: string[];
            /** Stability */
            stability: components["schemas"]["StabilityOut"][] | null;
            /** Stability Resamples */
            stability_resamples: number | null;
            /** Seed */
            seed: number | null;
        };
        /** OptimisedStrategyIn */
        OptimisedStrategyIn: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "optimised";
            objective?: components["schemas"]["ObjectiveIn"];
            constraints?: components["schemas"]["ConstraintsIn"];
        };
        /** PerformanceOut */
        PerformanceOut: {
            /** Observations */
            observations: number;
            /** Total Return */
            total_return: number;
            /** Cagr */
            cagr: number;
            /** Arithmetic Annual Return */
            arithmetic_annual_return: number;
            /** Annualised Volatility */
            annualised_volatility: number;
            sharpe_ratio: components["schemas"]["MetricOut"];
            sortino_ratio: components["schemas"]["MetricOut"];
            /** Max Drawdown */
            max_drawdown: number;
            calmar_ratio: components["schemas"]["MetricOut"];
            /** Var 95 */
            var_95: number;
            /** Cvar 95 */
            cvar_95: number;
            skewness: components["schemas"]["MetricOut"];
            excess_kurtosis: components["schemas"]["MetricOut"];
            /** Best Period */
            best_period: number;
            /** Worst Period */
            worst_period: number;
            /** Positive Periods Fraction */
            positive_periods_fraction: number;
            beta: components["schemas"]["MetricOut"] | null;
            /** Tracking Error */
            tracking_error: number | null;
            information_ratio: components["schemas"]["MetricOut"] | null;
        };
        /** PortfolioIn */
        PortfolioIn: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Dataset Id */
            dataset_id: string;
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** Spec */
            spec?: {
                [key: string]: unknown;
            } | null;
            /** Summary */
            summary?: {
                [key: string]: unknown;
            } | null;
        };
        /** PortfolioOut */
        PortfolioOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Dataset Id */
            dataset_id: string;
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** Spec */
            spec: {
                [key: string]: unknown;
            } | null;
            /** Summary */
            summary: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PortfolioResultOut */
        PortfolioResultOut: {
            /** Objective */
            objective: string;
            /** Expected Return */
            expected_return: number;
            /** Volatility */
            volatility: number;
            /** Sharpe Ratio */
            sharpe_ratio: number | null;
            /** Esg Score */
            esg_score: number | null;
            /** Esg Adjusted Return */
            esg_adjusted_return: number | null;
            /** Risk Free Rate */
            risk_free_rate: number;
            /** Diversification Ratio */
            diversification_ratio: number | null;
            /** Effective Number Of Assets */
            effective_number_of_assets: number;
            /** Holdings */
            holdings: components["schemas"]["HoldingOut"][];
            /** Sector Exposures */
            sector_exposures: components["schemas"]["SectorExposureOut"][];
            /** Diagnostics */
            diagnostics: components["schemas"]["ConstraintDiagnosticOut"][];
            /** Solver */
            solver: string;
            /** Warnings */
            warnings: string[];
        };
        /** PortfolioSpecIn */
        PortfolioSpecIn: {
            /** Name */
            name: string;
            /** Weights */
            weights: {
                [key: string]: number;
            };
        };
        /** ProvenanceOut */
        ProvenanceOut: {
            /** Source */
            source: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /** Adjustment */
            adjustment: string;
            /** Retrieved At */
            retrieved_at: string | null;
            /** License Note */
            license_note: string | null;
            /** Notes */
            notes: string[];
        };
        /** RebalanceEventOut */
        RebalanceEventOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Status */
            status: string;
            /** Turnover */
            turnover: number;
            /** Cost */
            cost: number;
            /**
             * Estimation Start
             * Format: date
             */
            estimation_start: string;
            /**
             * Estimation End
             * Format: date
             */
            estimation_end: string;
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** Message */
            message: string | null;
        };
        /**
         * RebalanceFrequency
         * @enum {string}
         */
        RebalanceFrequency: "monthly" | "quarterly" | "semiannual" | "annual";
        /** SectorExposureOut */
        SectorExposureOut: {
            /** Sector */
            sector: string;
            /** Weight */
            weight: number;
        };
        /** SectorLimitIn */
        SectorLimitIn: {
            /** Sector */
            sector: string;
            /** Min Weight */
            min_weight?: number | null;
            /** Max Weight */
            max_weight?: number | null;
        };
        /** SeriesOut */
        SeriesOut: {
            /** Name */
            name: string;
            /** Wealth */
            wealth: number[];
            /** Drawdown */
            drawdown: number[];
        };
        /**
         * SimulationMethod
         * @enum {string}
         */
        SimulationMethod: "parametric" | "bootstrap" | "block_bootstrap";
        /** StabilityOut */
        StabilityOut: {
            /** Ticker */
            ticker: string;
            /** Weight */
            weight: number;
            /** Mean */
            mean: number;
            /** P05 */
            p05: number;
            /** P50 */
            p50: number;
            /** P95 */
            p95: number;
            /** Frequency Held */
            frequency_held: number;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** User Id */
            user_id: string;
            /** Email */
            email: string;
        };
        /** TrackingErrorIn */
        TrackingErrorIn: {
            /**
             * Benchmark
             * @default equal_weight
             */
            benchmark: "equal_weight" | {
                [key: string]: number;
            };
            /** Max Tracking Error */
            max_tracking_error: number;
        };
        /** UniverseSelection */
        UniverseSelection: {
            /** Dataset Id */
            dataset_id: string;
            /** Tickers */
            tickers: string[];
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /**
             * Frequency
             * @default daily
             * @enum {string}
             */
            frequency: "daily" | "weekly" | "monthly";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeightChangeOut */
        WeightChangeOut: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string | null;
            /** Esg Score */
            esg_score: number | null;
            /** Baseline Weight */
            baseline_weight: number;
            /** Esg Weight */
            esg_weight: number;
            /** Change */
            change: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
        };
    };
    dev_login_api_v1_auth_dev_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_v1_datasets_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_dataset_api_v1_datasets_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_api_v1_datasets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_api_v1_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_api_v1_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_api_v1_analytics_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyticsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimise_api_v1_optimise_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimiseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimiseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    frontier_api_v1_frontier_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrontierRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrontierResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    esg_impact_api_v1_esg_impact_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EsgImpactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EsgImpactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    montecarlo_api_v1_montecarlo_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonteCarloRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonteCarloResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_api_v1_backtest_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_compare_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_portfolios_api_v1_portfolios_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_portfolio_api_v1_portfolios_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_api_v1_portfolios__portfolio_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_portfolio_api_v1_portfolios__portfolio_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_portfolio_api_v1_portfolios__portfolio_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_portfolio_api_v1_portfolios__portfolio_id__export_get: {
        parameters: {
            query?: {
                format?: "csv" | "json";
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
